### ISSUE TITLE
Duplicate functions

### ISSUE THREAD

**Issue by dsgpaiva** [MrGaabriel/KCurrencyConverter#1]
[CurrencyConverter.kt](https://github.com/MrGaabriel/KCurrencyConverter/blob/master/src/main/kotlin/net/mrgaabriel/currencyconverter/CurrencyConverter.kt) has two ``convert()`` functions.

**Comment by MrGaabriel** [comment]
Can you fix that for me?

**Comment by dsgpaiva** [comment]
Sure, which one do I remove?

**Comment by dsgpaiva** [comment]
I'm removing the 2nd, since it doesn't return the currency value multiplied by the value specified while calling the function.

**Comment by MrGaabriel** [comment]
In the `convert(integer, [...])`, just make it return `convert(int.toDouble(), [...]`)

**Comment by dsgpaiva** [comment]
oh

**Comment by dsgpaiva** [comment]
now that it's done, it's done
